### ISSUE TITLE
DLL name issue

### ISSUE THREAD

**Issue by DeeptiBhatia2906** [nviennot/jd-core-java#25]
This library is very useful and easy to use, exactly what I needed to decompile class files. 
Excellent work, Thank you!

We tried to build using gradle but we were unable to build due to following exception:
```
Note: ...\jd-core-java-master\src\main\java\com\intellij
\openapi\application\Application.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
:processResources UP-TO-DATE
:classes
:getNativeLibs FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':getNativeLibs'.
> A problem occurred starting process 'command 'hg''
```
Finally we were able to include the maven repository from [Versioneye] (https://www.versioneye.com/clojure/org.clojars.razum2um:jd-core-java/1.2)

While trying to use Decompiler, there was just a minor error that we got:
```
java.lang.UnsatisfiedLinkError: Can't load library: E:\bytecode-intelligence\bc-intell-package-analyzer\.\jd-intellij\src\main\native\nativelib\win32\x86_64\libjd-intellij.dll
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1825)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.System.load(System.java:1086)
	at com.jd.util.NativeUtils.loadLibraryFromJar(NativeUtils.java:73)
	at jd.ide.intellij.JavaDecompiler.<clinit>(JavaDecompiler.java:9)
	at jd.core.Decompiler.<init>(Decompiler.java:18)
```
We found that the dll was just named incorrectly. So we had go to this path and rename the dll 
from ``` jd-intellij.dll ```  to ``` libjd-intellij.dll ```

Please rename the dll in the repository so that everyone gets the correct dll.

Thanks once again!

**Comment by wawo00** [comment]
same error!!! u said that u went to this path ,and what is the "path",i want to fix it up,and it looked like that u guys have addressed this issue
